import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";
import { ThemeProvider } from "./components/ThemeProvider";
import { ThemeToggle } from "./components/ThemeToggle";
import { ReduxProvider } from "./redux/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased">
        <ReduxProvider>
          <ThemeProvider defaultTheme="system" storageKey="land3-theme">
            <header className="sticky top-0 z-10 w-full p-4 flex justify-between items-center bg-white dark:bg-gray-900 border-b border-gray-200 dark:border-gray-700 shadow-sm">
              <div className="flex items-center space-x-4">
                <div className="text-xl font-bold text-blue-800 dark:text-blue-400">
                  ລະບົບທີ່ດິນ
                </div>
                <nav className="hidden md:flex space-x-6 ml-8">
                  <Link href="/" className="text-gray-600 hover:text-blue-600 dark:text-gray-300 dark:hover:text-blue-400 transition-colors">
                    ໜ້າຫຼັກ
                  </Link>
                  <Link href="/land-management" className="text-gray-600 hover:text-blue-600 dark:text-gray-300 dark:hover:text-blue-400 transition-colors">
                    ຈັດການຂໍ້ມູນທີ່ດິນ
                  </Link>
                  <Link href="/documents-list" className="text-gray-600 hover:text-blue-600 dark:text-gray-300 dark:hover:text-blue-400 transition-colors">
                    ລາຍການເອກະສານ
                  </Link>
                  <Link href="/document-types" className="text-gray-600 hover:text-blue-600 dark:text-gray-300 dark:hover:text-blue-400 transition-colors">
                    ຈັດການເອກະສານ
                  </Link>
                </nav>
              </div>
              <ThemeToggle />
            </header>
            <main className="container mx-auto pt-4 pb-12">{children}</main>
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
